#
# Dockerfile
#
FROM sasan/virtualx:v1
MAINTAINER Khelender Sasan "ksasan@gmail.com"

# ---------------------------------------------------------------------------
# Setup environment variables
# ---------------------------------------------------------------------------
ARG username=user
ARG passwd=pass
ARG virtx=virtx
ARG dbHost=db
ENV	username=$username	\
	passwd=$passwd		\
	virtx=$virtx		\
	dbHost=$dbHost	


# --------------------
# Ruby related setup
# --------------------
SHELL	["/bin/bash", "-c"]
WORKDIR /var/www/virtualx
RUN export LANGUAGE=en_US.UTF-8         	\
        && export LANG=en_US.UTF-8      	\
        && export LC_ALL=en_US.UTF-8		\
	&& source /etc/profile.d/rvm.sh		\
	&& rvm install ruby-1.8.7		\
	&& rvm use ruby-1.8.7 --default 	\
	&& gem install gemset			\
	&& gem install bundle			\
	&& bundle install

RUN gem install rails --version 3.0.3	\
	&& cp /var/www/virtualx/config/database.yml.example /var/www/virtualx/config/database.yml \
	&& sed -i -re 's/\r//g ; s/host:\s*localhost/host: db/g ; s/database:.*/database: virtx/ ; s/username:.*/username: virtx/ ; s/password:.*/password: virtx/;' /var/www/virtualx/config/database.yml 

# ---------------------------------------------------------------------------
# Ports setup
# ---------------------------------------------------------------------------
EXPOSE 80 
EXPOSE 22 

#stuff for mysql
WORKDIR /
ADD ./mysql.sh /opt/mysql.sh  

CMD ["/usr/bin/supervisord"]

# -------------------------------------------------------------------------------
# Junk  / to be discarded
# -------------------------------------------------------------------------------
